services:
  app:
    image: parcel-react-1
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1234:1234"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
